In [10]:
library(dplyr)
## visualization
library(ggplot2)
library(ggplot2)
library(gridExtra)
library(dplyr)
library(ggplot2)
library(cowplot)

In [2]:
setwd("/home/liuxuan/metadata/PRJEB20213")
initial_meta<-read.csv("SraRunTable.csv",header = T)
head(initial_meta)

  Run        Assay.Type AvgSpotLen Bases    BioProject BioSample      Bytes
1 ERR1907465 AMPLICON   449         7339626 PRJEB20213 SAMEA103955437  3791943
2 ERR1907466 AMPLICON   412         4554387 PRJEB20213 SAMEA103955438  2389775
3 ERR1907467 AMPLICON   435        10169478 PRJEB20213 SAMEA103955439  5250508
4 ERR1907468 AMPLICON   457        24337195 PRJEB20213 SAMEA103955440 12063328
5 ERR1907469 AMPLICON   457        12659926 PRJEB20213 SAMEA103955441  6270490
6 ERR1907470 AMPLICON   458         6407084 PRJEB20213 SAMEA103955442  3316637
  Center.Name                       Collection_Date common_name ⋯ sample_name
1 AUSTRALIAN CENTRE FOR ECOGENOMICS 2014            human       ⋯ F01.d01
2 AUSTRALIAN CENTRE FOR ECOGENOMICS 2014            human       ⋯ F01.d02
3 AUSTRALIAN CENTRE FOR ECOGENOMICS 2014            human       ⋯ F01.d03
4 AUSTRALIAN CENTRE FOR ECOGENOMICS 2014            human       ⋯ F01.d05
5 AUSTRALIAN CENTRE FOR ECOGENOMICS 2014            human       ⋯ F01.d07
6 AUSTRALIAN CENTRE FOR ECOGENOMICS 2014            human       ⋯ F01.d08
  Sequencing_method SRA.Study Submitter_Id ENA_first_public
1 Illumina MiSeq    ERP022351 F01.d01      2019-04-02T17:03:53Z
2 Illumina MiSeq    ERP022351 F01.d02      2019-04-02T17:03:53Z
3 Illumina MiSeq    ERP022351 F01.d03      2019-04-02T17:03:53Z
4 Illumina MiSeq    ERP022351 F01.d05      2019-04-02T17:03:53Z
5 Illumina MiSeq    ERP022351 F01.d07      2019-04-02T17:03:53Z
6 Illumina MiSeq    ERP022351 F01.d08      2019-04-02T17:03:53Z
  ENA_last_update      scientific_name ENA_first_public.1 ENA_last_update.1
1 2017-04-03T00:34:28Z Homo sapiens
2 2017-04-03T00:34:28Z Homo sapiens
3 2017-04-03T00:34:28Z Homo sapiens
4 2017-04-03T00:34:28Z Homo sapiens
5 2017-04-03T00:34:28Z Homo sapiens
6 2017-04-03T00:34:28Z Homo sapiens
  INSDC_center_alias
1
2
3
4
5
6

In [3]:
colnames(initial_meta)

 [1] "Run"
 [2] "Assay.Type"
 [3] "AvgSpotLen"
 [4] "Bases"
 [5] "BioProject"
 [6] "BioSample"
 [7] "Bytes"
 [8] "Center.Name"
 [9] "Collection_Date"
[10] "common_name"
[11] "Consent"
[12] "DATASTORE.filetype"
[13] "DATASTORE.provider"
[14] "DATASTORE.region"
[15] "ENA.FIRST.PUBLIC..run."
[16] "ENA.LAST.UPDATE..run."
[17] "environment_.biome."
[18] "environment_.feature."
[19] "environment_.material."
[20] "Experiment"
[21] "external_id"
[22] "geo_loc_name_country"
[23] "geo_loc_name_country_continent"
[24] "geographic_location_.country_and.or_sea."
[25] "geographic_location_.latitude."
[26] "geographic_location_.longitude."
[27] "humam_oral_environmental_package"
[28] "INSDC_center_name"
[29] "INSDC_first_public"
[30] "INSDC_last_update"
[31] "INSDC_status"
[32] "Instrument"
[33] "Investigation_type"
[34] "Library.Name"
[35] "LibraryLayout"
[36] "LibrarySelection"
[37] "LibrarySource"
[38] "Organism"
[39] "Platform"
[40] "project_name"
[41] "ReleaseDate"
[42] "create_date"
[43] "version"
[44] "Sample.Name"
[45] "sample_name"
[46] "Sequencing_method"
[47] "SRA.Study"
[48] "Submitter_Id"
[49] "ENA_first_public"
[50] "ENA_last_update"
[51] "scientific_name"
[52] "ENA_first_public.1"
[53] "ENA_last_update.1"
[54] "INSDC_center_alias"

In [4]:
uniform_meta <- data.frame(
    BioProject = initial_meta$BioProject,
    Run = initial_meta$Run,
    sample_name = initial_meta$'sample_name',
    Age = NA,
    BMI = NA,
    Sex = NA,
    Region = "V3-V4",
    Platform = initial_meta$Platform,
    Country = initial_meta$'geographic_location_.country_and.or_sea.',
    Site = 'saliva',
    public_time = initial_meta$create_date,
    PCR_primers = 'F: TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGCCTACGGGNGGCWGCAG; R: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGGACTACHVGGGTATCTAATCC',
    title = 'Oxidative stress in the oral cavity is driven by individual-specific bacterial communities',
    Disease_study = "NO",
    Status = NA,
    matched_samples = 'NO')

In [5]:
head(uniform_meta)

  BioProject Run        sample_name Age BMI Sex Region Platform Country  Site
1 PRJEB20213 ERR1907465 F01.d01     NA  NA  NA  V3-V4  ILLUMINA Slovakia saliva
2 PRJEB20213 ERR1907466 F01.d02     NA  NA  NA  V3-V4  ILLUMINA Slovakia saliva
3 PRJEB20213 ERR1907467 F01.d03     NA  NA  NA  V3-V4  ILLUMINA Slovakia saliva
4 PRJEB20213 ERR1907468 F01.d05     NA  NA  NA  V3-V4  ILLUMINA Slovakia saliva
5 PRJEB20213 ERR1907469 F01.d07     NA  NA  NA  V3-V4  ILLUMINA Slovakia saliva
6 PRJEB20213 ERR1907470 F01.d08     NA  NA  NA  V3-V4  ILLUMINA Slovakia saliva
  public_time
1 2019-04-06T07:37:00Z
2 2019-04-06T07:37:00Z
3 2019-04-06T07:38:00Z
4 2019-04-06T12:10:00Z
5 2019-04-06T12:10:00Z
6 2019-04-06T12:10:00Z
  PCR_primers
1 F: TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGCCTACGGGNGGCWGCAG; R: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGGACTACHVGGGTATCTAATCC
2 F: TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGCCTACGGGNGGCWGCAG; R: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGGACTACHVGGGTATCTAATCC
3 F: TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGCCTACGGGNGGCWGCAG; R: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGGACTACHVGGGTATCTAATCC
4 F: TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGCCTACGGGNGGCWGCAG; R: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGGACTACHVGGGTATCTAATCC
5 F: TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGCCTACGGGNGGCWGCAG; R: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGGACTACHVGGGTATCTAATCC
6 F: TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGCCTACGGGNGGCWGCAG; R: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGGACTACHVGGGTATCTAATCC
  title
1 Oxidative stress in the oral cavity is driven by individual-specific bacterial communities
2 Oxidative stress in the oral cavity is driven by individual-specific bacterial communities
3 Oxidative stress in the oral cavity is driven by individual-specific bacterial communities
4 Oxidative stress in the oral cavity is driven by individual-specific bacterial communities
5 Oxidative stress in the oral cavity is driven by individual-specific bacterial communities
6 Oxidative stress in the oral cavity is driven by individual-specific bacterial communities
  Disease_study Status matched_samples
1 NO            NA     NO
2 NO            NA     NO
3 NO            NA     NO
4 NO            NA     NO
5 NO            NA     NO
6 NO            NA     NO

In [6]:
print(length(unique(uniform_meta$Run)))

print(length(unique(uniform_meta$sample_name)))

[1] 551
[1] 551

In [7]:
plot_data <- uniform_meta %>%
  select(-BioProject, -Run, -sample_name, -title)

In [8]:
create_simple_plots <- function(data) {
  plots <- list()
  
  for (col in colnames(data)) {
    # Check if the column is all NA
    if (all(is.na(data[[col]]))) {
      # Create an empty plot with text indicating all NA
      p <- ggplot() +
        annotate("text", x = 0.5, y = 0.5, label = "this column is NA", size = 6) +
        labs(title = col) +
        theme_void()
    } else if (is.numeric(data[[col]])) {
      # Numeric variable: histogram
      p <- ggplot(data, aes(x = .data[[col]])) +
        geom_histogram(fill = "blue", alpha = 0.6, bins = 20, na.rm = TRUE) +
        labs(title = col) +
        theme_minimal()
    } else {
      # Categorical variable: bar plot (remove NA values)
      count_data <- as.data.frame(table(data[[col]], useNA = "ifany"))
      p <- ggplot(count_data, aes(x = reorder(Var1, -Freq), y = Freq)) +
        geom_col(fill = "red", alpha = 0.6) +
        labs(title = col, x = NULL, y = "Count") +
        theme_minimal() +
        theme(axis.text.x = element_text(angle = 15, hjust = 1))
    }
    plots[[col]] <- p
  }
  
  return(plots)
}

In [11]:
plots <- create_simple_plots(plot_data)
p<-plot_grid(plots$Age, 
          plots$BMI, 
          plots$Sex, 
          plots$Region, 
          plots$Platform, 
          plots$Country, 
          plots$Site,
          plots$public_time, 
          plots$PCR_primers,
          plots$Disease_study,
          plots$Status,
          plots$matched_samples,# add 
          ncol = 3, align = "hv", axis = "lb")
ggsave("Metadata_Summary.png", plot = p, width = 8, height = 6, dpi = 150)

In [12]:
## uniform the column order
uniform_meta <- uniform_meta[, c("BioProject", "Run", "sample_name", "Age", "BMI", "Sex", "Region", "Platform", "Country", "Site", "public_time", "PCR_primers", "title", "Disease_study", "Status")]
write.csv(uniform_meta, file = "/home/liuxuan/metadata/PRJEB20213/uniform_meta.csv", quote = F)